Ecommerce/Web.UI/Areas/AdminPanel/Controllers/ProductCommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Services.Interfaces;
using System.Data;

namespace Web.UI.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = ("SuperAdmin,Admin"))]
    public class ProductCommentController : Controller
    {
        private readonly IProductCommentService _commentservice;

        public ProductCommentController(IProductCommentService commentservice)
        {
            _commentservice = commentservice;
        }


        public async Task<IActionResult> List(string search, int page = 1, int take = 15)
        {
            var list = await _commentservice.AllComments(search, page, take);

            return View(list);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _commentservice.RemoveAsync(id);

            return RedirectToAction("List");
        }
    }
}

Ecommerce/Web.UI/Areas/AdminPanel/Views/ProductComment/List.cshtml
@model Paginate<ProductCommentDto>
@{
    var count = 1;
}


<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4>Elaqeler</h4>
                  <div class="search-field ml-4 d-none d-md-block text-white" style="background: #495057d6;width:20%;height:40px;">
                     <form class="d-flex align-items-stretch h-100" asp-action="List" asp-controller="ProductComment" asp-area="AdminPanel">
                         <div class="input-group">
                             <input type="search" name="search" class="form-control bg-transparent border-0" placeholder="Mehsul'u axtarin...">
                             <div class="input-group-addon bg-transparent border-0 search-button">
                                 <button type="button" class="btn btn-sm bg-transparent px-0" style="color: #19f503;">
                                     <i class="mdi mdi-magnify"></i>
                                 </button>
                             </div>
                         </div>
                     </form>
                 </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>
                                    Mehsul
                                </th>
                                <th>
                                    Istifadeci
                                </th>
                                <th>
                                    Email
                                </th>
                                <th>
                                    Tarix
                                </th>
                                <th>
                                    Mesaj
                                </th>
                                 <th>
                                    Sil
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Datas)
                            {
                <tr>
                    <td>
                        @count
                    </td>
                    <td>
                        @(item.ProductName == null? "---" : item.ProductName)
                    </td>

                    <td>
                        @(item.Name == null? "---" : item.Name)
                    </td>
                    
                    <td>
                        @(item.Email == null? "---" : item.Email)
                    </td>
                    <td>
                        @item.CreateDate.ToString("dd MMM")
                    </td>
                    <td>
                        @(item.Description == null? "---" : item.Description)
                    </td>

                    <td>
                        <a asp-action="Delete" asp-controller="ProductComment" asp-area="AdminPanel" asp-route-id="@item.Id"><i class="bi bi-x-square"></i></a>
                    </td>
                </tr>count++;
                            }
                        </tbody>
                    </table>

                </div>
            </div>
            <div class="row my-3 justify-content-center">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination ">
                                <li class="page-item @(Model.HasPrevious ? "": "disabled")"> 
                                    <a class="page-link" style="color:black;" asp-action="List" asp-controller="ProductComment" asp-area="AdminPanel"
                                      
                                       asp-route-page="@(Model.CurrentPage-1)">Evvelki</a>
                                </li>
                                @for (int i = 1; i <= Model.TotalPage; i++)
                                {
                                    <li class="page-item @(i == Model.CurrentPage ? "disabled" : "")">
                                        <a class="page-link" asp-action="List" asp-area="AdminPanel" asp-controller="ProductComment"
                                          
                                           asp-route-page="@i">@i</a>
                                    </li>
                                }
                                <li class="page-item @(Model.HasNext ? "": "disabled")">
                                    <a class="page-link" style="color:black;" asp-action="List" asp-controller="ProductComment" asp-area="AdminPanel"
                                   
                                       asp-route-page="@(Model.CurrentPage+1)">Sonraki</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
        </div>
   </div>
</div>
            