Ecommerce/Web.UI/Areas/AdminPanel/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.DTOs;
using ServiceLayer.Services.Interfaces;
using System.Reflection.Metadata;

namespace Web.UI.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = ("SuperAdmin,Admin"))]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryservice;

        public CategoryController(ICategoryService categoryservice)
        {
            _categoryservice = categoryservice;
        }


        public async Task<IActionResult> List()
        {
            var categories = await _categoryservice.GetAllAsync();

            return View(categories);
        }

        public async Task<IActionResult> Create()
        {
            var list = await _categoryservice.GetAllAsync();

            return View((new CategoryCreateDto(), list));
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind(Prefix = "Item1")] CategoryCreateDto dto)
        {
            var list = await _categoryservice.GetAllAsync();
            if (!ModelState.IsValid) return View((dto, list));
            

            await _categoryservice.CreateAsync(dto);

            return RedirectToAction("Create");
        }

        public async Task<IActionResult> Update(int id)
        {
            var dto = await _categoryservice.GetByIdUpdate(id);
            var list = await _categoryservice.GetAllAsync();

            return View((dto, list));
        }
        [HttpPost]
        public async Task<IActionResult> Update([Bind(Prefix = "Item1")] CategoryUpdateDto dto)
        {
            var list = await _categoryservice.GetAllAsync();
            if (!ModelState.IsValid) return View((dto, list));

            await _categoryservice.Update(dto);

            return RedirectToAction("Update");
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id != 0)
            {
                await _categoryservice.Remove(id);
                return RedirectToAction("List");
            }

            return RedirectToAction("ErrorPage", "Home", new { area = "" });
        }

    }
}

Ecommerce/Web.UI/Areas/AdminPanel/Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Services.Interfaces;
using System.Data;

namespace Web.UI.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = ("SuperAdmin,Admin"))]
    public class ContactController : Controller
    {
        private readonly IContactService _contactservice;

        public ContactController( IContactService contactservice)
        {
            _contactservice = contactservice;
        }


        public async Task<IActionResult> List()
        {
            var categories = await _contactservice.GetAllAsync();

            return View(categories);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _contactservice.RemoveAsync(id);

            return RedirectToAction("List");
        }
    }
}

Ecommerce/Web.UI/Areas/AdminPanel/Controllers/UserController.cs
using DomainLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RepositoryLayer.Contexts;
using ServiceLayer.DTOs;

namespace Web.UI.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = ("SuperAdmin,Admin"))]
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;
        private readonly AppDbContext _context;
        public UserController(UserManager<AppUser> userManager, AppDbContext context, RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _context = context;
            _roleManager = roleManager;
        }


        public async Task<IActionResult> UserList()
        {

            //var users = _context.Users.Join(_context.UserRoles, user => user.Id, userRole => userRole.UserId, (user, userRole) => new
            //{
            //    user,
            //    userRole
            //}).Join(_context.Roles, two => two.userRole.RoleId, role => role.Id, (two, role) => new { two.user, two.userRole, role }).Where(x => x.role.Name != "SuperAdmin").Select(x => new AppUser
            //{
            //    Id = x.user.Id,
            //    UserName = x.user.UserName,
            //    Email = x.user.Email,
            //    AccessFailedCount = x.user.AccessFailedCount,
            //    PhoneNumber = x.user.PhoneNumber,
            //    PasswordHash = x.user.PasswordHash,
            //    LockoutEnabled = x.user.LockoutEnabled,
            //    LockoutEnd = x.user.LockoutEnd,
            //    NormalizedEmail = x.user.NormalizedEmail,
            //    Baskets = x.user.Baskets,
            //    Favorites = x.user.Favorites,
            //    EmailConfirmed = x.user.EmailConfirmed,
            //    ConcurrencyStamp = x.user.ConcurrencyStamp,
            //}).ToList();

            var filterusers = new List<AppUser>();

            var users = await _userManager.Users.ToListAsync();
            foreach (var user in users)
            {
                var userroles = await _userManager.GetRolesAsync(user);
                if (!userroles.Contains("SuperAdmin"))
                    filterusers.Add(user);
            }

            return View(filterusers);
        }


        public async Task<IActionResult> AssignRole(int id)
        {
            var user = await _userManager.Users.SingleOrDefaultAsync(x => x.Id == id);
            var userRoles = await _userManager.GetRolesAsync(user);
            var roles = await _roleManager.Roles.ToListAsync();

            var model = new RoleAssignSendModel();
            var list = new List<RoleAssingListModel>();

            foreach (var role in roles)
            {
                list.Add(new()
                {
                    RoleId = role.Id,
                    Name = role.Name,
                    Exist = userRoles.Contains(role.Name)
                });
            }

            model.Roles = list;
            model.UserId = id;

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AssignRole(RoleAssignSendModel model)
        {
            var user = await _userManager.Users.SingleOrDefaultAsync(x => x.Id == model.UserId);
            var userroles = await _userManager.GetRolesAsync(user);

            foreach (var role in model.Roles)
            {
                if (role.Exist)
                {
                    if (!userroles.Contains(role.Name))
                        await _userManager.AddToRoleAsync(user, role.Name);
                }
                else
                {
                    if (userroles.Contains(role.Name))
                        await _userManager.RemoveFromRoleAsync(user, role.Name);

                }
            }

            return RedirectToAction("UserList");
        }
    }
}

Ecommerce/Web.UI/Controllers/ProductController.cs
using DomainLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using ServiceLayer.DTOs;
using ServiceLayer.Services.Interfaces;

namespace Web.UI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productservice;
        private readonly IProductCommentService _commentservice;
        private readonly ICategoryService _categoryservice;

        public ProductController(IProductService productservice, IProductCommentService commentservice, ICategoryService categoryservice)
        {
            _productservice = productservice;
            _commentservice = commentservice;
            _categoryservice = categoryservice;
        }



        public async Task<IActionResult> AllList(string search, string sort, int page = 1, int take = 12)
        {
            ViewBag.Name = String.IsNullOrEmpty(sort) ? "name_desc" : "name_asc";
            ViewBag.Price = (sort == "price_desc") ? "price_asc" : "price_desc";
            ViewBag.Count = (sort == "count_desc") ? "count_asc" : "count_desc";

            //View send
            TempData["sort"] = sort;

            var products = await _productservice.AllHomeFilterAsync(search, sort, page, take);

            return View(products);
        }


        #region ProductCategory

        public async Task<IActionResult> ProductCategories(int id)
        {
            var list = await _categoryservice.CategoryProducts(id);

            return View(list);
        }


        #endregion


        #region DeatilandComment
        public async Task<IActionResult> ProductDetail(int id)
        {
            TempData["ProId"] = id;

            var product = await _productservice.GetByIdAsync(id);
            var comments = await _commentservice.ProductComment(id);

            return View((product, new ProductCommentCreateDto(), comments));
        }

        [HttpPost]
        public async Task<IActionResult> ProductDetail([Bind(Prefix = "Item2")] ProductCommentCreateDto dto)
        {
            if (TempData["ProId"] == null) return RedirectToAction("Index", "Home");

            dto.ProductId = (int)TempData["ProId"];

            var product = await _productservice.GetByIdAsync(dto.ProductId);
            var comments = await _commentservice.ProductComment(dto.ProductId);

            if (!ModelState.IsValid) return RedirectToAction("ProductDetail");

            await _commentservice.CreateAsync(dto);

            return RedirectToAction("ProductDetail");
        }

        #endregion

    }
}

Ecommerce/Web.UI/Areas/AdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/AdminPanel/node_modules/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/AdminPanel/node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.min.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="~/AdminPanel/node_modules/jquery-bar-rating/dist/themes/css-stars.css">
    <link rel="stylesheet" href="~/AdminPanel/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" />
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/AdminPanel/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/AdminPanel/images/favicon.png" />
    <!-- GetBootstrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">


</head>



<body>
    <div class="container-scroller">

        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" asp-action="Index" asp-controller="Dashboard" asp-area="AdminPanel"><img src="~/AdminPanel/images/logo.svg" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" asp-action="Index" asp-controller="Dashboard" asp-area="AdminPanel"><img src="~/AdminPanel/images/logo-mini.svg" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item dropdown">
                        <a class="nav-link nav-profile" id="profileDropdown" asp-action="Index" asp-controller="Home" asp-area="" data-toggle="dropdown" aria-expanded="false">
                            <span class="d-none d-lg-inline">Home Page</span>
                        </a>
                        
                    </li>
                </ul>
            </div>
        </nav>


        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <div class="row row-offcanvas row-offcanvas-right">
                <!-- partial:partials/_sidebar.html -->
                <nav class="sidebar sidebar-offcanvas" id="sidebar">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Dashboard" asp-area="AdminPanel">
                                <span class="menu-title">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="List" asp-controller="Category" asp-area="AdminPanel">
                                <span class="menu-title">Kateqoriyalar</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="List" asp-controller="Product" asp-area="AdminPanel">
                                <span class="menu-title">Mehsullar</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="List" asp-controller="ProductComment" asp-area="AdminPanel">
                                <span class="menu-title">Mehsul Commentleri</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="List" asp-controller="Contact" asp-area="AdminPanel">
                                <span class="menu-title">Contact</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="UserList" asp-controller="User" asp-area="AdminPanel">
                                <span class="menu-title">Istifadeciler</span>
                            </a>
                        </li>
                    </ul>
                    @*<div class="sidebar-progress">
                        <p>Total Sales</p>
                        <div class="progress progress-sm">
                            <div class="progress-bar bg-gradient-success" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p>50 Items sold</p>
                    </div>
                    <div class="sidebar-progress">
                        <p>Customer Target</p>
                        <div class="progress progress-sm">
                            <div class="progress-bar bg-gradient-primary" role="progressbar" style="width: 90%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p>200 Items sold</p>
                    </div>
                    <div class="wrapper upgrade-button">
                        <a href="~/AdminPanel/https://www.bootstrapdash.com/product/purple-bootstrap-4-admin-template/" target="_blank" class="btn btn-lg btn-block purchase-button">Upgrade To Pro</a>
                    </div>*@
                </nav>
                
    
                <!-- partial -->
                <div class="content-wrapper">
                   @RenderBody()
                </div>
                <!-- content-wrapper ends -->


                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="~/AdminPanel/https://www.bootstrapdash.com/" target="_blank">Bootstrap Dash</a>. All rights reserved.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- row-offcanvas ends -->
        </div>
        <!-- page-body-wrapper ends -->


    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/AdminPanel/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/AdminPanel/node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/AdminPanel/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/AdminPanel/node_modules/perfect-scrollbar/dist/js/perfect-scrollbar.jquery.min.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <script src="~/AdminPanel/node_modules/chart.js/dist/Chart.min.js"></script>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/AdminPanel/js/off-canvas.js"></script>
    <script src="~/AdminPanel/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/AdminPanel/js/dashboard.js"></script>
    <!-- End custom js for this page-->
</body>

</html>